apiVersion: v1
items:
- apiVersion: v1
  data:
    accounts.admin.enabled: "true"
    kustomize.buildOptions: --enable-helm
    resource.customizations.ignoreResourceUpdates.external-secrets.io_ExternalSecret: |
      jqPathExpressions:
      - .status.refreshTime
    resource.ignoreResourceUpdatesEnabled: "true"
    url: https://localhost:8080
  kind: ConfigMap
  metadata:
    annotations:
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    creationTimestamp: "2025-12-24T10:22:10Z"
    labels:
      app.kubernetes.io/name: argocd-cm
      app.kubernetes.io/part-of: argocd
    name: argocd-cm
    namespace: argocd
    resourceVersion: "591"
    uid: 1b79335b-4bfd-4914-a4b1-93178c26f493
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    creationTimestamp: "2025-12-24T10:22:10Z"
    labels:
      app.kubernetes.io/name: argocd-cmd-params-cm
      app.kubernetes.io/part-of: argocd
    name: argocd-cmd-params-cm
    namespace: argocd
    resourceVersion: "592"
    uid: f870a7d5-0fd7-4400-926b-7e7619394c0c
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    creationTimestamp: "2025-12-24T10:22:10Z"
    labels:
      app.kubernetes.io/name: argocd-gpg-keys-cm
      app.kubernetes.io/part-of: argocd
    name: argocd-gpg-keys-cm
    namespace: argocd
    resourceVersion: "593"
    uid: 68ad9f6a-cf54-4077-a77a-aae4dafd6cd5
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    creationTimestamp: "2025-12-24T10:22:10Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-cm
    namespace: argocd
    resourceVersion: "594"
    uid: c164bac4-3fa6-4d0d-96cb-73d28ea07079
- apiVersion: v1
  data:
    policy.csv: |
      g, admin, role:owner
      g, operator, role:operator
      g, viewer, role:viewer

      p, role:owner, applications, *, */*, allow

      p, role:owner, clusters, *, *, allow

      p, role:owner, repositories, *, *, allow

      p, role:owner, projects, *, *, allow

      p, role:owner, accounts, *, *, allow

      p, role:owner, gpgkeys, *, *, allow

      p, role:owner, logs, *, *, allow

      p, role:owner, exec, *, *, allow

      p, role:operator, applications, get, */*, allow
      p, role:operator, applications, list, */*, allow
      p, role:operator, applications, watch, */*, allow

      p, role:operator, applications, sync, */*, allow

      p, role:operator, applications, action/*, */*, allow

      p, role:operator, logs, get, */*, allow

      p, role:operator, applications, *, test-apps/*, allow

      p, role:viewer, applications, get, */*, allow
      p, role:viewer, applications, list, */*, allow
      p, role:viewer, applications, watch, */*, allow

      p, role:viewer, clusters, get, *, allow

      p, role:viewer, repositories, get, *, allow

      p, role:viewer, projects, get, *, allow

      p, role:readonly, applications, get, */*, allow
      p, role:readonly, applications, list, */*, allow
    policy.default: role:readonly
    scopes: '[groups]'
  kind: ConfigMap
  metadata:
    annotations:
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    creationTimestamp: "2025-12-24T10:22:10Z"
    labels:
      app.kubernetes.io/name: argocd-rbac-cm
      app.kubernetes.io/part-of: argocd
    name: argocd-rbac-cm
    namespace: argocd
    resourceVersion: "595"
    uid: a695117a-3f12-4b15-b71c-a1b3609aa10e
- apiVersion: v1
  data:
    ssh_known_hosts: |
      # This file was automatically generated by hack/update-ssh-known-hosts.sh. DO NOT EDIT
      [ssh.github.com]:443 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
      [ssh.github.com]:443 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      [ssh.github.com]:443 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      bitbucket.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPIQmuzMBuKdWeF4+a2sjSSpBK0iqitSQ+5BM9KhpexuGt20JpTVM7u5BDZngncgrqDMbWdxMWWOGtZ9UgbqgZE=
      bitbucket.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIazEu89wgQZ4bqs3d63QSMzYVa0MuJ2e2gKTKqu+UUO
      bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQeJzhupRu0u0cdegZIa8e86EG2qOCsIsD1Xw0xSeiPDlCr7kq97NLmMbpKTX6Esc30NuoqEEHCuc7yWtwp8dI76EEEB1VqY9QJq6vk+aySyboD5QF61I/1WeTwu+deCbgKMGbUijeXhtfbxSxm6JwGrXrhBdofTsbKRUsrN1WoNgUa8uqN1Vx6WAJw1JHPhglEGGHea6QICwJOAr/6mrui/oB7pkaWKHj3z7d1IC4KWLtY47elvjbaTlkN04Kc/5LFEirorGYVbt15kAUlqGM65pk6ZBxtaO3+30LVlORZkxOh+LKL/BvbZ/iRNhItLqNyieoQj/uh/7Iv4uyH/cV/0b4WDSd3DptigWq84lJubb9t/DnZlrJazxyDCulTmKdOR7vs9gMTo+uoIrPSb8ScTtvw65+odKAlBj59dhnVp9zd7QUojOpXlL62Aw56U4oO+FALuevvMjiWeavKhJqlR7i5n9srYcrNV7ttmDw7kf/97P5zauIhxcjX+xHv4M=
      github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
      gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
      gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
      ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
      vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
  kind: ConfigMap
  metadata:
    annotations:
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    creationTimestamp: "2025-12-24T10:22:10Z"
    labels:
      app.kubernetes.io/name: argocd-ssh-known-hosts-cm
      app.kubernetes.io/part-of: argocd
    name: argocd-ssh-known-hosts-cm
    namespace: argocd
    resourceVersion: "596"
    uid: f6892bb3-5039-475f-8448-b56f68f9c076
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      argocd.version: v2.10.17
      demo.upgrade.step: initial
    creationTimestamp: "2025-12-24T10:22:10Z"
    labels:
      app.kubernetes.io/name: argocd-tls-certs-cm
      app.kubernetes.io/part-of: argocd
    name: argocd-tls-certs-cm
    namespace: argocd
    resourceVersion: "598"
    uid: 05c931ea-e94e-49fa-819b-a36ebf2d7da1
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI1MTIyMzEwMjEwOVoXDTM1MTIyMjEwMjEwOVowFTETMBEGA1UE
      AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOjy
      vSS3SfMgsDfgkvWFsBXM0Tst+uQeSgT1ar1fXyHkrMaAf/3ZzW1n33pW8lbr7GCc
      26FBocM5KRqahHzwnq51Bge1Nc+BtSaSK2+t8OQgbmdryiXmoWVBonaoLhWepymS
      cvlZsgiRj/8NInsRqzhLxKh9xR8wgND/U1CtYEg9wA44U/dxW0/nA0njHApAk3/x
      iEyqwWIDRC/Q5PyFn2CFWaeuy5+kV1SEWDZ+kTaRNXAdmPJZmi8frOXviLVExgJE
      +U26Qkx05Nunbt9gTho6kPoiAc0RSui4SSIVcZ5SdaNpFU4QRWfv6SMtxY68/PpO
      bPULNzBjLIy5bYMzdS8CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
      MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
      BBR1fIZdyplBMGVU8zq/ieUGTgVRhDANBgkqhkiG9w0BAQsFAAOCAQEAWmx134DH
      Q/qhZrvBSyc3WxvK3N8s6C36CuFfJMfPKg2zp1UA9VcYpyzbvAgMGwJJ8/KgDheG
      veFPYL8jkKJJpQqaxmVndPyQL21XJP2wAMmjaQCk0L/u7sr7dIsEPOxLUepTlcAf
      w3npR6YRA4OfoSEWgpny2NwfBAnx2oY6kCEwsmov+egALOFBKAiqdYeieGsRlgaY
      B2WioYLXDl+qDVX7DhjVWnFcX287SA89+py5DWGitt+TGqE6sdGPLwqXrDGdukaG
      MIDzZA4Ry34afju/aVl3/bndgm2yKhXbV1N5CB2Z6VNDoQg6zo/CUqw5F23wQRtK
      LmSFrYpzFoGYyw==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-12-24T10:22:10Z"
    name: kube-root-ca.crt
    namespace: argocd
    resourceVersion: "559"
    uid: 77e9bfdf-4985-4458-94be-7e9fc4028d26
kind: List
metadata:
  resourceVersion: ""
